name = "raylib"
description = "Ada wrapper to raylib, a library to enjoy games programming"
version = "3.0.0"
website = "https://github.com/AntonMeep/raylib"
licenses = "Zlib"
tags = ["game", "gamedev", "graphics", "opengl"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

[gpr-externals]
RAYLIB_OS = ["windows", "linux", "macos"]
[gpr-set-externals."case(os)".windows]
RAYLIB_OS = "windows"
[gpr-set-externals."case(os)".linux]
RAYLIB_OS = "linux"
[gpr-set-externals."case(os)".macos]
RAYLIB_OS = "macos"
