name = "raylib"
description = "Ada wrapper to raylib, a library to enjoy games programming"
version = "3.0.0"
website = "https://github.com/AntonMeep/raylib"
licenses = "Zlib"
tags = ["game", "gamedev", "graphics", "opengl"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]
