name = "raylib"
description = "Ada wrapper to raylib, a library to enjoy games programming"
version = "0.0.0"

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]
