name = "raygen"
description = "Generator of an Ada wrapper to raylib based on raylib parser json"
version = "0.0.0"

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

executables = ["raygen"]

[[depends-on]]
parse_args = "~0.9.0"
json = "^5.0.1"
