name = "raylib_examples"
description = "Examples of RayLib crate usage"
version = "0.0.0"

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

executables = ["core_basic_window"]

[configuration]
disabled = true

[[depends-on]]
raylib = "*"

[[pins]]
raylib = {path = "../"}
